server {
  listen 80;
  server_name _;

  absolute_redirect off;

  add_header Access-Control-Allow-Origin * always;
  add_header Access-Control-Allow-Methods "GET,POST,PUT,PATCH,DELETE,OPTIONS" always;
  add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
  if ($request_method = OPTIONS) { return 204; }

  # ----- MÉDICOS -----
  location = /api/medicos { return 307 /api/medicos/; }
  location /api/medicos/ {
    # Mapea /api/medicos/... del gateway a /api/medicos/... del servicio
    proxy_pass http://mcs-medicos:8082/api/medicos/;
  }

  # ----- PACIENTES -----
  location = /api/pacientes { return 307 /api/pacientes/; }
  location /api/pacientes/ {
    proxy_pass http://mcs-pacientes:8083/api/pacientes/;
  }

  # ----- NOTIFS (si expone /api/notifs/**) -----
  location = /api/notifs { return 307 /api/notifs/; }
  location /api/notifs/ {
    proxy_pass http://mcs_notificaciones:8084/api/notifs/;
  }

  # ----- AGENDAMIENTO (si expone /api/**) -----
  location = /api { return 307 /api/; }
  location /api/ {
    proxy_pass http://mcs_agendamiento:8081/api/;
  }
}
