server {
  listen 80;
  server_name _;

  # --- Oculta headers CORS que envían los microservicios ---
  proxy_hide_header Access-Control-Allow-Origin;
  proxy_hide_header Access-Control-Allow-Methods;
  proxy_hide_header Access-Control-Allow-Headers;
  proxy_hide_header Access-Control-Allow-Credentials;

  # --- CORS centralizado en el gateway ---
  # Permite solo tu frontend; 
  set $cors_origin "";
  if ($http_origin ~* "^http://(localhost|127\.0\.0\.1):5173$") { set $cors_origin $http_origin; }

  add_header Access-Control-Allow-Origin $cors_origin always;
  add_header Vary Origin always;
  add_header Access-Control-Allow-Methods "GET,POST,PUT,PATCH,DELETE,OPTIONS" always;
  add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
  add_header Access-Control-Allow-Credentials "true" always;  
  add_header Access-Control-Max-Age 600 always;

  # Responder preflight sin ir al backend
  if ($request_method = OPTIONS) { return 204; }

  # --- Rutas (sin redirecciones) ---
  location = /api/medicos   { proxy_pass http://mcs-medicos:8082/api/medicos; }
  location  /api/medicos/   { proxy_pass http://mcs-medicos:8082/api/medicos/; }

  location = /api/pacientes { proxy_pass http://mcs-pacientes:8083/api/pacientes; }
  location  /api/pacientes/ { proxy_pass http://mcs-pacientes:8083/api/pacientes/; }

  location = /api/turnos    { proxy_pass http://mcs-agendamiento:8081/api/turnos; }
  location  /api/turnos/    { proxy_pass http://mcs-agendamiento:8081/api/turnos/; }

  location = /api/notifs    { proxy_pass http://mcs-notificaciones:8084/api/notifs; }
  location  /api/notifs/    { proxy_pass http://mcs-notificaciones:8084/api/notifs/; }
}
