server.port=${PORT:8081}

# MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql}:3306/${DB_NAME:agendadb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.datasource.hikari.initializationFailTimeout=0

# REST de otros MCS
clients.medicos-url=${MEDICOS_URL:http://mcs_medicos:8082}
clients.pacientes-url=${PACIENTES_URL:http://mcs_pacientes:8083}

# RabbitMQ (publica evento cita.confirmada)
spring.rabbitmq.host=${RABBIT_HOST:rabbit}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}
app.rabbit.exchange=${RABBIT_EXCHANGE:citas.exchange}
app.rabbit.routing.citaConfirmada=${RABBIT_ROUTING_CITA:cita.confirmada}
